# Generated by Django 4.1.7 on 2023-05-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_posttype2_sesizarefunctionar1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='isInterestPoint',
            field=models.BooleanField(default=False),
        ),
    ]
