# Generated by Django 4.1.7 on 2023-05-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_point_label_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesizarefunctionar1',
            name='points',
            field=models.ManyToManyField(blank=True, to='api.point'),
        ),
        migrations.AddField(
            model_name='sesizarefunctionar2',
            name='points',
            field=models.ManyToManyField(blank=True, to='api.point'),
        ),
    ]
